In [1]:
import pandas as pd
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [7]:
df = pd.DataFrame({ 'Gender' : ['Male', 'Female', 'Male', 'Female', 'Female','Female'],
                       'Size' : ['XL','S','M','XL','M','L'],
                        'City' : ['KTM','PKR','BRT','KTM','PKR','BRT'] })
df.head(6)

Gender Size City
0    Male   XL  KTM
1  Female    S  PKR
2    Male    M  BRT
3  Female   XL  KTM
4  Female    M  PKR
5  Female    L  BRT

In [6]:
size_mapping={'XL':4,'L':3,'M':2,'S':1}

In [8]:
df['Size']=df['Size'].map(size_mapping)
df.head(6)

Gender  Size City
0    Male     4  KTM
1  Female     1  PKR
2    Male     2  BRT
3  Female     4  KTM
4  Female     2  PKR
5  Female     3  BRT

In [20]:
X=df[['Gender','Size','City']].values
X

array([['Male', 4, 'KTM'],
       ['Female', 1, 'PKR'],
       ['Male', 2, 'BRT'],
       ['Female', 4, 'KTM'],
       ['Female', 2, 'PKR'],
       ['Female', 3, 'BRT']], dtype=object)

In [21]:
# city encode
city_encoder = LabelEncoder()
X[:,2] = city_encoder.fit_transform(X[:,2])
X

array([['Male', 4, 1],
       ['Female', 1, 2],
       ['Male', 2, 0],
       ['Female', 4, 1],
       ['Female', 2, 2],
       ['Female', 3, 0]], dtype=object)

In [22]:
# Size encode
size_OneHot = OneHotEncoder()
Y= size_OneHot.fit_transform(X[:,1].reshape(-1,1)).toarray()
Y

array([[0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [23]:
# Size encode
size_OneHot = OneHotEncoder()
X= size_OneHot.fit_transform(X).toarray()
X

array([[0., 1., 0., 0., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 1., 0., 1., 0.],
       [1., 0., 0., 1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0., 1., 0., 0.]])

In [18]:
from numpy import array
# define example
data = ["Small" , "Medium" , "Large" , "Small" , "XL" , "Medium" , "Large" , "Small" , "Large" , "XL" ]
values = array(data)
print(values)

['Small' 'Medium' 'Large' 'Small' 'XL' 'Medium' 'Large' 'Small' 'Large'
 'XL']


In [19]:
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)

[2 1 0 2 3 1 0 2 0 3]


In [20]:
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

[[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]
