In [1]:
# Load libraries
import pandas as pd
from sklearn.model_selection import train_test_split    # Import train_test_split function
from sklearn import metrics                             #Import scikit-learn metrics module for accuracy calculation
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
# load dataset
data = pd.read_csv("D:\Dataset\iris.csv")
data.head()

sepal length  sepal width  petal length  petal width  classes
0           5.1          3.5           1.4          0.2        1
1           4.9          3.0           1.4          0.2        1
2           4.7          3.2           1.3          0.2        1
3           4.6          3.1           1.5          0.2        1
4           5.0          3.6           1.4          0.2        1

In [3]:
#split dataset in features and target variable
feature_cols = ['sepal length', 'sepal width', 'petal length', 'petal width']
X = data[feature_cols] # Features
y = data.classes # Target variable
# print(X,y)

In [4]:
# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=1)

In [7]:
classifier = SVC(kernel='linear', random_state = 1)
classifier.fit(X_train,y_train)


y_pred=classifier.predict(X_test) 

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 1.0
[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        11
           2       1.00      1.00      1.00        13
           3       1.00      1.00      1.00         6

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [8]:
classifier = SVC(kernel='rbf', random_state = 1)
classifier.fit(X_train,y_train)


y_pred=classifier.predict(X_test) 

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.9666666666666667
[[11  0  0]
 [ 0 12  1]
 [ 0  0  6]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        11
           2       1.00      0.92      0.96        13
           3       0.86      1.00      0.92         6

    accuracy                           0.97        30
   macro avg       0.95      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30



In [9]:
# load dataset
data = pd.read_csv("D:\Dataset\diabetes.csv")
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [11]:
#split dataset in features and target variable
X = data.iloc[:, :-1].values
y = data.iloc[:, 8].values

In [12]:
# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=1)

In [13]:
classifier = SVC(kernel='sigmoid', random_state = 1)
classifier.fit(X_train,y_train)


y_pred=classifier.predict(X_test) 

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.5064935064935064
[[75 24]
 [52  3]]
              precision    recall  f1-score   support

           0       0.59      0.76      0.66        99
           1       0.11      0.05      0.07        55

    accuracy                           0.51       154
   macro avg       0.35      0.41      0.37       154
weighted avg       0.42      0.51      0.45       154



In [14]:
classifier = SVC(kernel='rbf', random_state = 1)
classifier.fit(X_train,y_train)


y_pred=classifier.predict(X_test) 

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.7857142857142857
[[93  6]
 [27 28]]
              precision    recall  f1-score   support

           0       0.78      0.94      0.85        99
           1       0.82      0.51      0.63        55

    accuracy                           0.79       154
   macro avg       0.80      0.72      0.74       154
weighted avg       0.79      0.79      0.77       154



In [15]:
classifier = SVC(kernel='linear', random_state = 1)
classifier.fit(X_train,y_train)


y_pred=classifier.predict(X_test) 

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.7792207792207793
[[89 10]
 [24 31]]
              precision    recall  f1-score   support

           0       0.79      0.90      0.84        99
           1       0.76      0.56      0.65        55

    accuracy                           0.78       154
   macro avg       0.77      0.73      0.74       154
weighted avg       0.78      0.78      0.77       154



In [17]:
classifier = SVC(kernel='poly', random_state = 1, C=2.0)
classifier.fit(X_train,y_train)


y_pred=classifier.predict(X_test) 

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.7857142857142857
[[95  4]
 [29 26]]
              precision    recall  f1-score   support

           0       0.77      0.96      0.85        99
           1       0.87      0.47      0.61        55

    accuracy                           0.79       154
   macro avg       0.82      0.72      0.73       154
weighted avg       0.80      0.79      0.77       154

